# Generated by Django 5.0.4 on 2024-05-02 08:22

import firma.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("firma", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", firma.models.CustomUserManager()),
            ],
        ),
    ]
