# Generated by Django 5.0.4 on 2024-05-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firma", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
