# Generated by Django 5.0.4 on 2024-05-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firma", "0003_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(),
        ),
    ]
