# Generated by Django 5.0.4 on 2024-05-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firma", "0004_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(default="ram", max_length=200),
        ),
        migrations.AddField(
            model_name="product",
            name="producer",
            field=models.CharField(default="GOODRAM", max_length=200),
        ),
    ]
