# Generated by Django 5.0.4 on 2024-05-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firma", "0005_product_category_product_producer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(default="Opis", max_length=10000),
        ),
    ]
